### ISSUE TITLE
Support for www.NHK-OnDemand.jp (enhancement)

### ISSUE THREAD

**Issue by peterjc** [sbroenne/plugin.video.nhkworldtv#103]
Have you ever looked at www.NHK-OnDemand.jp (use of which I believe is geographically restricted to Japan only) which offers a few videos for free, but otherwise charges a small fee per video, or a monthly fee?

I'm hoping there is an API behind this is similar to NHK World, and that you might be able to handle it too?

**Comment by sbroenne** [comment]
Hi Peter, thanks for the suggestion but the design goal for the add-in is only to include content from the NHK World web site itself.
