### ISSUE TITLE
Newsline Asia not updating

### ISSUE THREAD

**Issue by saud-kh** [sbroenne/plugin.video.nhkworldtv#19]
all 'news program' section updates regularly (daily) but the newline Asia program hasn't changed in months. not sure if its an error in the extension or perhaps it hasn't updated since November?

**Comment by sbroenne** [comment]
Unfortunately, the last News Line Asia 24 was broadcasted on January 8th according to NHK API and NHK App. That is also the one displayed in the plugin.  So looks like it hasn't been updated in a while :(
