### ISSUE TITLE
NHK Live stream currently not working

### ISSUE THREAD

**Issue by anaselyousfi** [sbroenne/plugin.video.nhkworldtv#5]
This link seems to work: https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8

**Comment by sbroenne** [comment]
Hi @anaselyousfi , thanks for reporting and the new link! This has been fixed by the latest release 0.0.125 - if you installed from my dev-repo the plugin should auto-update itself.

Stefan
