### ISSUE TITLE
NHK addon on demand episodes fail to update

### ISSUE THREAD

**Issue by Jez76** [sbroenne/plugin.video.nhkworldtv#71]
Hi, sorry to bother you and thanks for the fantastic addon! One small thing - the on demand episodes have failed to update for a few weeks. Is this an NHK issue or an addon issue? Thanks again for an excellent addon! Cheers, Jez

**Comment by sbroenne** [comment]
@Jez76 - thanks for reporting this. NHK has changed their API to a new version. While the old API still works, it only returns stale information. I am checking now how to fix this.

**Comment by Jez76** [comment]
Thanks a lot Stefan. New content is now available for me too so all seems working. Misty’s addon has the same issue so I’ll let them know as well. Thanks for taking the time to fix it so quickly and thanks again for your excellent addon! Cheers, Jez

**Comment by sbroenne** [comment]
Thank you, Jez! Glad that you enjoy the add-on!
