### ISSUE TITLE
‘News programs’ no longer loading after last update

### ISSUE THREAD

**Issue by saud-kh** [sbroenne/plugin.video.nhkworldtv#9]
Hello! There seems to be an issue with ‘new programs’ section after the new update as it doesn’t load!

**Comment by sbroenne** [comment]
This is a new bug caused by a change in the NHK API. I will investigate.

**Comment by sbroenne** [comment]
@saud-kh Hi Saud, it seems that the NHK API sometimes return a News Program that does not exist (this is where the 404 Error comes from). The plug-in now silently ignores these programs. I have just pushed version 0.0.127 to the repo.

**Comment by saud-kh** [comment]
sbroenne .. you're a legend! thank you so much for this awesome add-on and fixing this so quickly!
