### ISSUE TITLE
With Cache Enabled on 1.0.9 Error is thrown on startup

### ISSUE THREAD

**Issue by BuckShotSX** [sbroenne/plugin.video.nhkworldtv#90]
Hi,
Thanks for your work on this plugin, it's great and thanks for fixing the other issue.

I am still experiencing an error on launch with the cache enabled.

Environment:
NHK World TV 1.0.9
Windows 10 21H2 (kernel: Windows NT 10.0.19044.1889)
Kodi 19.3.0

Error from log is attached.

[NHK 1.0.9 error.txt](https://github.com/sbroenne/plugin.video.nhkworldtv/files/9558352/NHK.1.0.9.error.txt)

**Comment by sbroenne** [comment]
Sorry for the late reply but I cannot reproduce this. It looks like this was a temporary data error in the NHK API.

Glad that you are enjoying the plugin and thanks for reporting these issues!!
