### ISSUE TITLE
Can't connect to repository

### ISSUE THREAD

**Issue by xyzy-web** [sbroenne/plugin.video.nhkworldtv#95]
Hello,

just tried to install from the repo on Kodi 20 (Sony Android TV) and get an error that connection to the repository is not possible.
Is this a problem with Kodi 20 or am I doing something the wrong way here?
I already tried killing and restarting Kodi.

Best regards

**Comment by xyzy-web** [comment]
Tried downgrading to 19.5, now the repo works.
However there is an error when trying to launch the plugin after installing it.
Doesnt go away after restart of Kodi either.

**Comment by sbroenne** [comment]
@xyzy-web : I am able to reproduce the error. Working on a fix.

**Comment by sbroenne** [comment]
@xyzy-web: I have uploaded a new version of the repository that works for Nexus. This repo will then allow you to update the plug-in to 1.0.11 which fixes the start-up issue.

Unfortunately, the repo does not update itself so you need download & install it yourself.

https://bit.ly/3ZCz8b8

or

https://github.com/sbroenne/kodirepo/raw/main/repository.sbroenne/repository.sbroenne-0.0.16.zip
